services:
  bootstrap-node:
    image: kadlab:latest 
    stdin_open: true
    tty: true
    networks:
      - kademlia_network
    environment:
      - ALPHA=3 # Number of nodes to contact in parallel
      - B=20    # Number of bytes in the key
      - K=20    # Number of nodes to store in the routing table
      - IS_BOOTSTRAP_NODE=true
      - BOOTSTRAP_PORT=4000
      - BOOTSTRAP_ID=FFFFFFFF00000000000000000000000000000000

  kademlia-node:
    image: kadlab:latest
    stdin_open: true
    tty: true
    depends_on:
      - bootstrap-node
    networks:
      - kademlia_network
    environment:
      - ALPHA=3
      - B=20
      - K=20
      - IS_BOOTSTRAP_NODE=false
      - BOOTSTRAP_IP=bootstrap-node
      - BOOTSTRAP_PORT=4000
      - BOOTSTRAP_ID=FFFFFFFF00000000000000000000000000000000
      
networks:
  kademlia_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.1.0/24

