version: "3.7"
services:
  bootstrap-node:
    image: kadlab:latest 
    stdin_open: true
    tty: true
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
    networks:
      - kademlia_network
    environment:
      - ALPHA=3
      - B=160
      - K=20
      - IS_BOOTSTRAP_NODE=true
      - BOOTSTRAP_PORT=4000
      - BOOTSTRAP_ID=FFFFFFFF00000000000000000000000000000000

  kademliaNodes:
    image: kadlab:latest
    stdin_open: true
    tty: true
    deploy:
      mode: replicated
      replicas: 3 
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
    depends_on:
      - bootstrap-node
    networks:
      - kademlia_network
    environment:
      - ALPHA=3
      - B=160
      - K=20
      - IS_BOOTSTRAP_NODE=false
      - BOOTSTRAP_IP=bootstrap-node
      - BOOTSTRAP_PORT=4000
      - BOOTSTRAP_ID=FFFFFFFF00000000000000000000000000000000
      
networks:
  kademlia_network:
    driver: overlay
    ipam:
      config:
        - subnet: 10.1.1.0/24

